spring:
   output:
      ansi:
         enabled: always
server:
   port: 8091
   #output:
    #  ansi:
     #    enabled: always   
logging:
   level:
      root: ERROR
      com:
         davalores: TRACE
   pattern:
      console: "%clr(%d{mm:ss.SSS}){yellow} %clr(%.-3level) %clr(%-35.35logger{0}) %msg %n"