spring:
   application:
      name: cryptoOrchestrator
   datasource:
      url: jdbc:sqlserver://192.168.12.71:1433;databaseName=RipioQA;encrypt=false;trustServerCertificate=false;
      username: ${EMPLEADORES_BACK_DATABASE_USER:RipioQA}
      password: ${EMPLEADORES_BACK_DATABASE_PASS:RipioQA2026}
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
   jpa:
      properties:
         hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.SQLServerDialect
         database-platform: org.hibernate.dialect.SQLServerDialect
      show-sql: true
server:
   port: 8091
   servlet:
      context-path: /crypto
apis:
   esco-bolsa:
      protocolo: http
      dominio: 192.168.12.51:6003
      api-version: 9
      urls:
         login: /api/v9/login
login:
   token:
      secreto: Scre-to.159-AuZ-tero.753xFRD345dfr#456x
      expiracion: 500
   tokenRefresco:
      expiracion: 500