package com.davalores.crypto.orchestrator.domain.model.exception;

public enum ErrorCodeEnum {	 

	HTTP_UNAUTHORIZED_ERROR("HTTP_UNAUTHORIZED_ERROR"),	
	HTTP_DFA_UNAUTHORIZED_ERROR("HTTP_DFA_UNAUTHORIZED_ERROR"),
	HTTP_LOGIN_TIMEOUT_ERROR("HTTP_LOGIN_TIMEOUT_ERROR"),
	HTTP_NOT_FOUND("HTTP_ERROR_404"),
	HTTP_ERROR("HTTP_ERROR"),
	JPA_ERROR("JPA_ERROR"),
	JSON_MAPPER_SERIALIZE_ERROR("JSON_MAPPER_SERIALIZE_ERROR"),
	JSON_MAPPER_DESERIALIZE_ERROR("JSON_MAPPER_DESERIALIZE_ERROR"),
	JSON_PROC_ERROR("JSON_PROC_ERROR"), 
	UNEXPECTED_ERROR("UNEXPECTED_ERROR"),
	INPUT_PARAM_REQUIRED_ERROR("INPUT_PARAM_REQUIRED_ERROR"),
	CONFIGURATION_ERROR("CONFIGURATION_ERROR"),
	BUSINESS_ERROR("BUSINESS_ERROR"),
	NO_DATA_FOUND_ERROR("NO_DATA_FOUND_ERROR")
	;
	
	private String type;
	 
	ErrorCodeEnum(String type) {
        this.type = type;
    }
 
    public String getType() {
        return type;
    }
	 
}
